version: "3"

services:
  tindev-backend:
    container_name: tindev-backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/usr/src/app/
      - /usr/src/app/node_modules
    ports:
      - "3333:3333"
  tindev-frontend:
    container_name: tindev-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/usr/src/app/
      - /usr/src/app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - tindev-backend
